In [1]:
import pandas as pd
table = pd.read_excel('Final.xlsx')
table

,OBJECTID,Name,SUM_Pop_Estimate,Pop_den,Medical_percent,Post_percent,Service_percent,Police_percent,Market_Count,Food_Count,Shop_Count,Leisure_Count,Trip_Count,Rent_price,Shape_Length,Shape_Area,Noise
0,1,香港鐵路北角站 : 0 - 500,67239,0.126217,0.474378,0.371411,0.947921,0.039422,3,1,34,20,0,11210,3896.047442,5.327267e+05,56.230358
1,2,香港鐵路柴灣站 : 0 - 500,47604,0.084305,0.931740,0.253047,0.474309,0.142061,1,3,23,36,1,10422,3617.032608,5.646660e+05,64.950845
2,3,香港鐵路堅尼地城站 : 0 - 500,44027,0.093047,0.772557,0.863348,0.975081,0.000000,1,1,19,26,0,16869,3360.251673,4.731708e+05,63.718801
3,4,香港鐵路金鐘站 : 0 - 500,5258,0.008006,0.666055,0.602971,0.375013,0.294676,0,0,17,19,1,22132,3910.125813,6.567648e+05,71.163704
4,5,香港鐵路炮台山站 : 0 - 500,58368,0.105366,0.000000,0.950699,0.851785,0.000000,2,1,33,19,0,13354,3231.012032,5.539543e+05,64.628026
5,6,香港鐵路上環站 : 0 - 500,17354,0.024781,0.989853,0.923230,0.714010,0.269329,3,2,65,33,6,17866,4715.554507,7.003026e+05,64.542016
6,7,香港鐵路筲箕灣站 : 0 - 500,61338,0.093875,0.621106,0.805978,0.990321,0.000050,2,1,21,35,0,11189,3990.187436,6.533988e+05,62.492963
7,8,香港鐵路太古站 : 0 - 500,68101,0.125874,0.136444,0.335932,0.882748,0.287523,1,1,24,13,0,13808,3631.567701,5.410236e+05,58.931917
8,9,香港鐵路天后站 : 0 - 500,29129,0.056570,0.218456,0.924522,0.466104,0.000000,1,0,22,49,0,12729,3922.015383,5.149204e+05,66.888222
9,10,香港鐵路銅鑼灣站 : 0 - 500,33889,0.041714,0.472819,0.684943,0.500940,0.000000,3,1,69,18,2,9739,4081.787526,8.124151e+05,69.922883
10,11,香港鐵路灣仔站 : 0 - 500,38069,0.046770,0.891451,0.939613,0.785953,0.216650,3,1,54,47,5,15985,3844.722072,8.139612e+05,67.182939
11,12,香港鐵路西灣河站 : 0 - 500,59518,0.101828,0.659073,0.744650,0.992961,0.350354,1,1,20,27,0,11083,3651.579864,5.844951e+05,61.932536
12,13,香港鐵路西營盤站 : 0 - 500,71191,0.075860,0.811189,0.613530,0.591146,0.489792,2,2,38,61,1,15895,4058.518586,9.384493e+05,59.704936
13,14,香港鐵路香港大學站 : 0 - 500,71949,0.089460,0.422337,0.533308,0.926274,0.344933,1,1,32,36,0,17929,4459.426243,8.042547e+05,61.388360
14,15,香港鐵路杏花邨站 : 0 - 500,15415,0.053322,0.000000,0.730895,0.805647,0.000000,0,0,5,7,0,11812,2805.567781,2.890935e+05,57.236332
15,16,香港鐵路鰂魚涌站 : 0 - 500,40677,0.070071,0.377555,0.654656,0.670933,0.415245,2,1,24,17,1,13586,4300.542880,5.805152e+05,62.881904
16,17,香港鐵路中環站 : 0 - 500,5999,0.005971,0.607302,0.755537,0.696875,0.175361,1,0,60,39,6,13480,4681.271452,1.004673e+06,69.358779

In [2]:
copy_table = table.copy()
data = table.drop(['OBJECTID', 'Name', 'SUM_Pop_Estimate', 'Shape_Length', 'Shape_Area'], axis = 1)
data

,Pop_den,Medical_percent,Post_percent,Service_percent,Police_percent,Market_Count,Food_Count,Shop_Count,Leisure_Count,Trip_Count,Rent_price,Noise
0,0.126217,0.474378,0.371411,0.947921,0.039422,3,1,34,20,0,11210,56.230358
1,0.084305,0.931740,0.253047,0.474309,0.142061,1,3,23,36,1,10422,64.950845
2,0.093047,0.772557,0.863348,0.975081,0.000000,1,1,19,26,0,16869,63.718801
3,0.008006,0.666055,0.602971,0.375013,0.294676,0,0,17,19,1,22132,71.163704
4,0.105366,0.000000,0.950699,0.851785,0.000000,2,1,33,19,0,13354,64.628026
5,0.024781,0.989853,0.923230,0.714010,0.269329,3,2,65,33,6,17866,64.542016
6,0.093875,0.621106,0.805978,0.990321,0.000050,2,1,21,35,0,11189,62.492963
7,0.125874,0.136444,0.335932,0.882748,0.287523,1,1,24,13,0,13808,58.931917
8,0.056570,0.218456,0.924522,0.466104,0.000000,1,0,22,49,0,12729,66.888222
9,0.041714,0.472819,0.684943,0.500940,0.000000,3,1,69,18,2,9739,69.922883
10,0.046770,0.891451,0.939613,0.785953,0.216650,3,1,54,47,5,15985,67.182939
11,0.101828,0.659073,0.744650,0.992961,0.350354,1,1,20,27,0,11083,61.932536
12,0.075860,0.811189,0.613530,0.591146,0.489792,2,2,38,61,1,15895,59.704936
13,0.089460,0.422337,0.533308,0.926274,0.344933,1,1,32,36,0,17929,61.388360
14,0.053322,0.000000,0.730895,0.805647,0.000000,0,0,5,7,0,11812,57.236332
15,0.070071,0.377555,0.654656,0.670933,0.415245,2,1,24,17,1,13586,62.881904
16,0.005971,0.607302,0.755537,0.696875,0.175361,1,0,60,39,6,13480,69.358779

In [3]:
colomn = data.columns.tolist()
colomn

['Pop_den',
 'Medical_percent',
 'Post_percent',
 'Service_percent',
 'Police_percent',
 'Market_Count',
 'Food_Count',
 'Shop_Count',
 'Leisure_Count',
 'Trip_Count',
 'Rent_price',
 'Noise']

In [4]:
data_normalized = data[colomn].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
data_normalized

,Pop_den,Medical_percent,Post_percent,Service_percent,Police_percent,Market_Count,Food_Count,Shop_Count,Leisure_Count,Trip_Count,Rent_price,Noise
0,1.000000,0.479240,0.169661,0.927114,0.080488,1.000000,0.333333,0.453125,0.240741,0.000000,0.118696,0.000000
1,0.651447,0.941291,0.000000,0.160685,0.290043,0.333333,1.000000,0.281250,0.537037,0.166667,0.055112,0.583961
2,0.724148,0.780476,0.874793,0.971065,0.000000,0.333333,0.333333,0.218750,0.351852,0.000000,0.575325,0.501458
3,0.016922,0.672882,0.501574,0.000000,0.601635,0.000000,0.000000,0.187500,0.222222,0.166667,1.000000,1.000000
4,0.826600,0.000000,1.000000,0.771541,0.000000,0.666667,0.333333,0.437500,0.222222,0.000000,0.291697,0.562343
5,0.156427,1.000000,0.960627,0.548585,0.549885,1.000000,0.666667,0.937500,0.481481,1.000000,0.655773,0.556584
6,0.731039,0.627473,0.792559,0.995727,0.000102,0.666667,0.333333,0.250000,0.518519,0.000000,0.117002,0.419371
7,0.997153,0.137843,0.118805,0.821647,0.587030,0.333333,0.333333,0.296875,0.111111,0.000000,0.328331,0.180908
8,0.420796,0.220695,0.962479,0.147409,0.000000,0.333333,0.000000,0.265625,0.777778,0.000000,0.241265,0.713696
9,0.297248,0.477666,0.619070,0.203782,0.000000,1.000000,0.333333,1.000000,0.203704,0.333333,0.000000,0.916909
10,0.339297,0.900589,0.984109,0.665007,0.442331,1.000000,0.333333,0.765625,0.740741,0.833333,0.503994,0.733431
11,0.797177,0.665829,0.704653,1.000000,0.715311,0.333333,0.333333,0.234375,0.370370,0.000000,0.108448,0.381842
12,0.581220,0.819504,0.516709,0.349758,1.000000,0.666667,0.666667,0.515625,1.000000,0.166667,0.496732,0.232672
13,0.694324,0.426666,0.401721,0.892084,0.704243,0.333333,0.333333,0.421875,0.537037,0.000000,0.660857,0.345402
14,0.393784,0.000000,0.684937,0.696877,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.167272,0.067364
15,0.533071,0.381425,0.575659,0.478874,0.847797,0.666667,0.333333,0.296875,0.185185,0.166667,0.310417,0.445416
16,0.000000,0.613527,0.720259,0.520855,0.358031,0.333333,0.000000,0.859375,0.592593,1.000000,0.301864,0.879135

In [5]:
weights = {
    'Pop_den': 0.02941,            
    'Medical_percent': 0.14706,
    'Post_percent': 0.02941,
    'Service_percent': 0.08824,
    'Police_percent': 0.14706,
    'Market_Count': 0.08824,
    'Food_Count':0.14705,
    'Shop_Count': 0.14706,
    'Leisure_Count': 0.08824,
    'Trip_Count': 0.02941,
    'Rent_price': -0.02941,
    'Noise': -0.02941
}
sum(abs(value) for value in weights.values())

1.0

In [6]:
data_normalized['Sum_Score'] = sum(data_normalized[col] * weight for col, weight in weights.items())
data_normalized['Sum_Score']

0     0.420167
1     0.465737
2     0.357467
3     0.195944
4     0.288475
5     0.669568
6     0.399551
7     0.328838
8     0.195167
9     0.400305
10    0.598420
11    0.466678
12    0.635107
13    0.435529
14    0.086317
15    0.406148
16    0.412781
Name: Sum_Score, dtype: float64

In [7]:
result = pd.DataFrame({
    'OBJECTID': table['OBJECTID'],
    'Name':table['Name'],
    'Score': data_normalized['Sum_Score']
})
result

    OBJECTID                 Name     Score
0          1    香港鐵路北角站 : 0 - 500  0.420167
1          2    香港鐵路柴灣站 : 0 - 500  0.465737
2          3  香港鐵路堅尼地城站 : 0 - 500  0.357467
3          4    香港鐵路金鐘站 : 0 - 500  0.195944
4          5   香港鐵路炮台山站 : 0 - 500  0.288475
5          6    香港鐵路上環站 : 0 - 500  0.669568
6          7   香港鐵路筲箕灣站 : 0 - 500  0.399551
7          8    香港鐵路太古站 : 0 - 500  0.328838
8          9    香港鐵路天后站 : 0 - 500  0.195167
9         10   香港鐵路銅鑼灣站 : 0 - 500  0.400305
10        11    香港鐵路灣仔站 : 0 - 500  0.598420
11        12   香港鐵路西灣河站 : 0 - 500  0.466678
12        13   香港鐵路西營盤站 : 0 - 500  0.635107
13        14  香港鐵路香港大學站 : 0 - 500  0.435529
14        15   香港鐵路杏花邨站 : 0 - 500  0.086317
15        16   香港鐵路鰂魚涌站 : 0 - 500  0.406148
16        17    香港鐵路中環站 : 0 - 500  0.412781

In [8]:
result.to_excel('Result_Score.xlsx', index = False)